name: Project Work 6 - CI

on:
  # On every push to the main brand, execute
  push:
    branches:
      - main

jobs:
  CI-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # Run tests (installation of dependencies is in tests.sh)
    - name: Tests feedback
      run: |
        chmod +x project/tests.sh
        project/tests.sh